services:

  postgres:
    image: postgres:16
    container_name: finxguard-postgres
    environment:
      POSTGRES_DB: frauddb
      POSTGRES_USER: frauduser
      POSTGRES_PASSWORD: fraudpass
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redpanda:
    image: docker.redpanda.com/redpandadata/redpanda:v26.2.3
    container_name: finxguard-redpanda
    command:
      - redpanda
      - start
      - --kafka-addr
      - internal://0.0.0.0:9092,external://0.0.0.0:19092
      - --advertise-kafka-addr
      - internal://redpanda:9092,external://localhost:19092
      - --mode
      - dev-container
      - --smp
      - "1"
    ports:
      - "19092:19092"
    volumes:
      - redpanda_data:/var/lib/redpanda/data

  redis:
    image: redis:7
    container_name: finxguard-redis
    ports:
      - "6379:6379"

volumes:
  postgres_data:
  redpanda_data: