spring.application.name=finxguard-backend

spring.datasource.url=jdbc:postgresql://localhost:5432/frauddb
spring.datasource.username=frauduser
spring.datasource.password=fraudpass
spring.datasource.driver-class-name=org.postgresql.Driver